### ISSUE TITLE
Add Assets

### ISSUE THREAD

**Issue by ted537** [skycoin/cx-game#280]
We have many furniture-style asset on the Zoho drive. Add these in.

It probably makes sense to formalize the process / structure for registering, loading, and unloading these items as well.

**Comment by ted537** [comment]
# Relevant directories

Taken from a snapshot of the `kcg/luis` workdrive directory on July 29

- computers
- containers
- doors
- elavator
- enemies/grasshopper
- furniture
- gas_machines
- grenades
- guns
- liquid_machines
- map_lab_objects
- mining_laser
- operation_table
- pipesim
- plants
- power_machines
- radar
- radio
- solid_machines
- spheroid_lander
- swords
- terrains
- terrains_fluids
- turrets
- vehicles
- vines

# Note

Skipping vehicles and other complicated assets for now

**Comment by ted537** [comment]
```yaml
---                                                                                                                                    
                                                                                                                                       
width: 128                                                                                                                             
height: 96                                                                                                                             
                                                                                                                                       
cellwidth: 32                                                                                                                          
cellheight: 32                                                                                                                         
                                                                                                                                       
name: containers                                                                                                                       
                                                                                                                                       
sprites:                                                                                                                               
    orangebucket:                                                                                                                      
        unit: grid                                                                                                                     
        left: 0                                                                                                                        
        top: 0                                                                                                                         
                                                                                                                                       
    ac-unit:                                                                                                                           
        unit: grid                                                                                                                     
        left: 0                                                                                                                        
        top: 2                                                                                                                         
        width: 2                                                                                                                       
        height: 1                                                                                                                      
                                                                                                                                       
--- 
```

WIll probably use a format like this to describe sprites. Image dimensions are included such that the configuration is stable across rescaling.
